### ISSUE TITLE
URL bindings are to the legacy API

### ISSUE THREAD

**Issue by nwolverson** [purescript-node/purescript-node-url#14]
[From the url documentation page](https://nodejs.org/api/url.html#legacy-url-api)

v15.13.0, v14.17.0 | Deprecation revoked. Status changed to "Legacy".
-- | --
v11.0.0 | This API is deprecated.

> Legacy: Use the WHATWG URL API instead.

Bindings in URL also use the `querystring` module (and perhaps should have been in a separate PureScript module originally)

> The querystring API is considered Legacy. While it is still maintained, new code should use the [<URLSearchParams>](https://nodejs.org/api/url.html#class-urlsearchparams) API instead.

**Comment by JordanMartinez** [comment]
Fixed in #20.
