### ISSUE TITLE
Implement `URLSearchParams`

### ISSUE THREAD

**Issue by CGenie** [purescript-node/purescript-node-url#18]
https://nodejs.org/api/url.html#class-urlsearchparams

We currently have `Query` as a very thin wrapper around nodejs `querystring`:

https://github.com/purescript-node/purescript-node-url/blob/v6.0.0/src/Node/URL.js#L2

Apparently this is legacy in the API:

https://nodejs.org/api/url.html#legacy-urlobject

It would be useful to implement `URLSearchParams` especially that I can't find anything for query manipulation on Pursuit. Query is bit tricky: there is URL escaping and whatnot. And it's often necessary when writing frontends that make requests for the backend.

**Comment by JordanMartinez** [comment]
Fixed in #20.
